receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: info
  awsxray:
    region: ap-southeast-1
  awsemf:
    region: ap-southeast-1

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - logging
        - awsemf