kind: Service
apiVersion: v1
metadata:
  name: worker-service
  labels:
    app: workerservice
spec:
  selector:
    app: workerservice
  ports:
  - protocol: TCP
    port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  labels:
    app: workerservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: workerservice
  template:
    metadata:
      labels:
        app: workerservice
    spec:
      containers:
      - name: workerservice
        image: 783560535431.dkr.ecr.ap-southeast-1.amazonaws.com/worker-service:${IMAGE_TAG}
        imagePullPolicy: Always
        env:
        - name: DOTNET_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: microservice-configmap
              key: DOTNET_ENVIRONMENT

        - name: MassTransit__AwsAccessKey
          valueFrom:
            secretKeyRef:
              name: microservice-basic-auth-secret
              key: AwsAccessKey
        - name: MassTransit__AwsSecretKey
          valueFrom:
            secretKeyRef:
              name: microservice-basic-auth-secret
              key: AwsSecretKey
        - name: MassTransit__AwsRegion
          valueFrom:
            secretKeyRef:
              name: microservice-basic-auth-secret
              key: AwsRegion
        - name: MassTransit__IsUsingAmazonSQS
          value: "true"
        - name: MassTransit__IsUsingRabbitMQ
          value: "false"
        - name: Serilog__WriteTo__0__Args__path
          value: "./logs/NET6.Microservice.WorkerService.logs.json"

        - name: OpenTelemetry__OtelCollector
          valueFrom:
            configMapKeyRef:
              name: microservice-configmap
              key: OTEL_EXPORTER
        - name: OpenTelemetry__IsAWSExporter
          value: "true"
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
